/*
 * Commitlint 配置
 * @generated by @robot-admin/git-standards
 *
 * 直接修改此文件即可自定义提交校验规则
 */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  plugins: [{ rules: { 'subject-chinese': ({ subject }) => [/[\u3400-\u9fff]/u.test(subject || ''), '提交描述请使用中文，技术标识可保留英文'] } }],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'wip', 'feat', 'fix', 'docs', 'style', 'refactor',
        'perf', 'test', 'chore', 'revert', 'build', 'deps',
      ],
    ],
    'scope-empty': [2, 'never'],
    'subject-case': [0],
    'subject-chinese': [2, 'always'],
  },
}
