packages:
  - "."

overrides:
  "brace-expansion@<1.1.16": 1.1.16
  "brace-expansion@>=3.0.0 <5.0.7": 5.0.7
  esbuild: ^0.25.12
  "js-yaml@>=4.0.0 <4.3.0": 4.3.0
  tmp: ^0.2.7
  vite: ^6.4.3

allowBuilds:
  esbuild: true
